---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 9
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hello-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend
        image: gcr.io/google-samples/hello-app:2.0
        ports:
          - containerPort: 80
        env:
          - name: PORT
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - name: hello-app
    port: 80
---
